gitlabs ci changes

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -27,19 +27,30 @@ variables:
   # NPM_JF_RT_REPO: ""
   # DOCKER_JF_RT_REPO: ""
 
+
+OIDC:
+
 build-job:
   stage: npm_build
   image: node:lts
-  script:
+  before_script:
     - apt-get -y update && apt-get -y install jq
     - echo "Build triggered by commit - "${CI_COMMIT_SHA}" on branch - ${CI_COMMIT_BRANCH} by ${CI_COMMIT_AUTHOR}"
     - |
       JF_ACCESS_TOKEN=$(curl -X POST -H "Content-Type: application/json" "https://${JF_URL}/access/api/v1/oidc/token" -d "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\", \"subject_token\": \"${GITLAB_OIDC_TOKEN}\", \"provider_name\": \"rkfrog-gitlab\"}")
-      echo ${JF_ACCESS_TOKEN} | jq -r '.access_token'
+      if [[ -n $(echo ${JF_ACCESS_TOKEN} | jq -r '.access_token') ]]; then
+        export JF_ACCESS_TOKEN=$(echo ${JF_ACCESS_TOKEN} | jq -r '.access_token')
+        echo "OIDC Access token from JFrog generated successfully"
+      else
+        echo "Failed to get OIDC token from JFrog"
+        exit 1
+      fi
     - !reference [.setup_jfrog, script] # install JF-CLI v2
+  script:
     - jf --version
     - ls -la /builds/${CI_PROJECT_PATH}
     # - env
+    - jf c add --url https://${JF_URL} --access-token ${JF_ACCESS_TOKEN} --interactive=false
     - jf c show
     - jf rt ping
     # - jf npm-config --repo-deploy=$NPM_JF_RT_REPO -repo-resolve=$NPM_JF_RT_REPO
